### ISSUE TITLE
when trying to evaluate on SemEval there is error in rifre_sentence.py

### ISSUE THREAD

**Issue by michal-olek** [zhao9797/RIFRE#2]
I am very interested in the code and I was trying to run it but after all necessary preparations I got error:

Stack trace is:

=== Epoch 0 train ===
  0%|                                                                                                                                        | 0/1084 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    framework.train_semeval_model()
  File "/home/michalolek/NLPWR/projects/RIFRE/RIFRE/framework/sentence_re.py", line 114, in train_semeval_model
    self.train_once(self.train_singla_loader, warmup)
  File "/home/michalolek/NLPWR/projects/RIFRE/RIFRE/framework/sentence_re.py", line 147, in train_once
    logits, _ = self.model(sent_label, *args)
  File "/home/michalolek/anaconda3/envs/RIFRE2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michalolek/NLPWR/projects/RIFRE/RIFRE/models/rifre_sentence.py", line 20, in forward
    logits = self.gat(x, pos1, pos2, mask)
  File "/home/michalolek/anaconda3/envs/RIFRE2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michalolek/NLPWR/projects/RIFRE/RIFRE/models/rifre_sentence.py", line 37, in forward
    p = torch.arange(self.config.class_nums, device=x.device).long()
AttributeError: 'str' object has no attribute 'device'

And in that place x is just a string "last_hidden_state"

I downloaded both versions of BERT and started program with:
python train.py --datatset semeval

**Comment by michal-olek** [comment]
This is due different handling code in Python 1.3
when changing in bert_encoder merthod forward to:

  def forward(self, token, att_mask):
        outputs = self.bert(token, attention_mask=att_mask)
        return outputs[0];


it works.
